# Generated by Django 5.2.5 on 2025-09-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
    ]
