# Generated by Django 5.2.5 on 2025-09-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tenant",
            new_name="Organization",
        ),
        migrations.RenameField(
            model_name="membership",
            old_name="tenant",
            new_name="organization",
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together={("organization", "user")},
        ),
    ]
