# Generated by Django 5.2.5 on 2025-09-12 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_membership_role"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="membership",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="user",
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
        migrations.DeleteModel(
            name="Membership",
        ),
    ]
